### ISSUE TITLE
Error search 

### ISSUE THREAD

**Issue by rpinto18** [jd-alexander/Google-Directions-Android#15]
Help please

http://oi60.tinypic.com/4gp0zs.jpg

Error contacting API:
Status{statusCode=PLACES_API_KEY_INVALID, resolution=null}

**Comment by jd-alexander** [comment]
You are receiving that error because you haven't placed an API key in the manifest file. Go to the Google API Console and ensure that you enable Google Places API for Android.  Follow the official guide if you aren't sure what to do. 
https://developers.google.com/places/android/signup

Once you get the API key, place it in this tag of the manifest.
`<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="API_KEY_HERE"/>`

**Comment by rpinto18** [comment]
Thanks , I am newbie jeje

**Comment by jd-alexander** [comment]
Great! Glad I could help.
