### ISSUE TITLE
simple example problem

### ISSUE THREAD

**Issue by harryRichardIzquierdo** [jd-alexander/Google-Directions-Android#41]
I have a simple example, but I have problems, do me a great favor if you help me.
![problema](https://cloud.githubusercontent.com/assets/8239437/12153067/ea380160-b485-11e5-8f03-5c67b481560a.PNG)

**Comment by fcduarte** [comment]
@jd-alexander I don't know if it's related but the README is outdated when it describes the `onRoutingSuccess` listener .. it should be `public void onRoutingSuccess(ArrayList<Route> route, int shortestRouteIndex)`

maybe that is the problem @harryRichardIzquierdo is having because seems like he copy-pasted the sample.

**Comment by harryRichardIzquierdo** [comment]
you're right, thank you very much for your help, but not solved, wanted a simple example to go slowly understanding.
I want to have 3 LatLng for the road is generated.

**Comment by fcduarte** [comment]
Check out the whole repository and look the `MainActivity` class from the
sample module .. It'll help to start.

**Comment by jd-alexander** [comment]
I'm sorry I haven't updated the readme. I am gonna do so now.
