### ISSUE TITLE
Remove a route?

### ISSUE THREAD

**Issue by exside** [jd-alexander/Google-Directions-Android#5]
Is it somehow possible to remove a route when another marker on a map is clicked? I have 9 markers to which the route from the current position can be asked by the user, but they just add up on top of each other (depending on the route/location). I would like to display just the route to the last clicked marker...tried to assign the Routing to a variable and then set this to null onMarkerClick but that didn't work. Any hints?

**Comment by brusasu** [comment]
Hi, thanks for this library that works perfect. I have a question and i hope you can get me into the right way.

I draw a route from two point (fixed), and clicking in the infoview the route (polyline) will drawn into the map and it works. By the way i have 20 different marker, and i want to draw a route only when click on the infoview. I mean, if there is already a route in the map, clicking in one other infoview, this route have to be removed and the new one has to be added in the map.

I have a Switch-case method to call each route by clicking in the infoview of the marker, this is a snippet of my code:

switch (markerIndex){
case 0:

                    start = new LatLng(22.28861858, 11.32771726);
                    end = new LatLng(22.48861858, 11.36779726);

                    Routing routing = new Routing(Routing.TravelMode.WALKING);
                    routing.registerListener(ActivityOutdoor.this);
                    routing.execute(start, end);

                    break;
                case 1:
                    start = new LatLng(21.48861858, 11.32771726);
                    end = new LatLng(23.48861858, 13.36779726);

                    Routing routing1 = new Routing(Routing.TravelMode.WALKING);
                    routing1.registerListener(ActivityOutdoor.this);
                    routing1.execute(start, end);
                    break;

                default:
                    break;


            }
Do you know how to remove the previous route, when click the other infoview?
I used map.clear(); but it will delete all the content of the map
Thanks in advance
Brus

**Comment by alhinai-hamed** [comment]
I'm not sure if this would work.. Though try to free the routing object object before plotting routing1
Or 
rather than declaring routing1.. Overwrite routing and the previous one should disappear

Hope this gives u a slight idea ..

One more thing.. There's a lot of redundancy,. U can declare start, end and routing outside the switch statement.. 
Have the switch cases involve with start and end only .. once the values are selected.. Initialize routing outside the switch and start calling routing functions. Note that This way you are only storing one route.

I am not a contributor, though I got a similar project.
